import Head from "next/head";
import Main from "~/@/components/main";
import { Toaster } from "~/@/components/ui/toaster";

export default function Home() {
  return (
    <>
      <Head>
        <title>Api Keys</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Main />
        <Toaster />
      </main>
    </>
  );
}
