import Head from "next/head";
import ApiKeyComponent from "~/@/components/api-key-component";

const APPLICATION_ID = "exa.3iIYtEcNcxF3AMfKCIF3d6";
const TOKEN =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBsaWNhdGlvblVzZXIiOnsiaWQiOiIzYTNhZjgwOC1lZTJmLTQwZTktYTcwNC01ZGU5NjJkMWFjNDgiLCJjcmVhdGVkQXQiOiIyMDIzLTA5LTA2VDAwOjMyOjA4LjkxN1oiLCJ1cGRhdGVkQXQiOiIyMDIzLTA5LTA2VDAwOjMyOjA4LjkxN1oiLCJkZWxldGVkQXQiOm51bGwsImFwcGxpY2F0aW9uVXNlckZvcmVpZ25JZCI6InRlc3QtMTIiLCJtZXRhZGF0YSI6bnVsbH0sImFwcGxpY2F0aW9uIjp7ImlkIjoiZjRmNTYwZjctZDQ3NC00ZDA0LWFlMzktMzJhZTdjY2I4MGU3IiwiY3JlYXRlZEF0IjoiMjAyMy0wOS0wNlQwMDozMTo1My45OTFaIiwidXBkYXRlZEF0IjoiMjAyMy0wOS0wNlQwMDozMTo1My45OTFaIiwiZGVsZXRlZEF0IjpudWxsLCJuYW1lIjoiRXhhbSIsImRlc2NyaXB0aW9uIjoiIiwicHVibGljSWQiOiJleGEuM2lJWXRFY05jeEYzQU1mS0NJRjNkNiIsIm9yZ2FuaXphdGlvbiI6eyJpZCI6IjI2NjU0OWUwLTZhN2QtNGJlOS1iOTYwLTA5MzhiZjljYzUwZCIsImNyZWF0ZWRBdCI6IjIwMjMtMDktMDZUMDA6MzE6MTQuMjI2WiIsInVwZGF0ZWRBdCI6IjIwMjMtMDktMDZUMDA6MzE6MTQuMjI2WiIsImRlbGV0ZWRBdCI6bnVsbCwibmFtZSI6IlRlc3QifSwiaXBSYXRlTGltaXQiOjEwLCJiYXNlVXJsIjp7ImlkIjoiNTFjNTg4YWItM2Y2YS00OGMzLWI4YzMtNDBlODY0OTIwYWNkIiwiY3JlYXRlZEF0IjoiMjAyMy0wOS0wNlQwMDozMTo1My45OTFaIiwidXBkYXRlZEF0IjoiMjAyMy0wOS0wNlQwMDozMTo1My45OTFaIiwiZGVsZXRlZEF0IjpudWxsLCJ1cmwiOiJodHRwczovL2dvb2dsZS5jb20ifSwiYW1vdW50UGVySW50ZXJ2YWwiOm51bGwsInRpbWVJbnRlcnZhbCI6IlNFQ09ORCJ9LCJpYXQiOjE2OTY5ODU0MTksImV4cCI6MTY5OTU3NzQxOX0.C9n7P6I1_OF4ulrJY6Zal1vDtEWPfVGUDsfM-hilC1U";

export default function Home() {
  return (
    <>
      <Head>
        <title>Api Keys</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ApiKeyComponent applicationId={APPLICATION_ID} token={TOKEN} />
      </main>
    </>
  );
}
